INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M001', 'S004', 500, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M002', 'S004', 500, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M002', 'S005', 30, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M003', 'S004', 1, 'g  '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M004', 'S004', 50, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M005', 'S006', 200, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M005', 'S004', 330, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M006', 'S003', 500, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M007', 'S003', 500, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M007', 'S006', 300, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M008', 'S003', 400, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M008', 'S006', 200, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M008', 'S005', 8, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M009', 'S003', 330, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M009', 'S006', 200, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M010', 'S007', 10, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M011', 'S007', 5, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M012', 'S007', 10, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M012', 'S008', 25, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M013', 'S008', 50, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M014', 'S009', 10, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M015', 'S009', 20, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M016', 'S010', 100, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M017', 'S011', 10, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M018', 'S011', 10, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M018', 'S001', 30, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M019', 'S001', 100, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M020', 'S001', 100, 'mg '); 
INSERT INTO COMPOSITION ( NRMEDICAMENT, NRSUBSTANCE, QUANTITE, UNITE ) VALUES ( 
'M021', 'S002', 500, 'mg '); 
COMMIT;
 
