INSERT INTO fabricants (nrfabricant,nom) VALUES (01,'UPSA_MEDICA');
INSERT INTO fabricants (nrfabricant,nom) VALUES (02,'WARNER LAMBERT HC');
INSERT INTO fabricants (nrfabricant,nom) VALUES (03,'ROCHE CONSUMER HC');
INSERT INTO fabricants (nrfabricant,nom) VALUES (04,'PHARMATHIC');
INSERT INTO fabricants (nrfabricant,nom) VALUES (05,'WYETH LEDERLE');
INSERT INTO fabricants (nrfabricant,nom) VALUES (06,'MERCK');
INSERT INTO fabricants (nrfabricant,nom) VALUES (07,'MSD');
INSERT INTO fabricants (nrfabricant,nom) VALUES (08,'PFIZER');
INSERT INTO fabricants (nrfabricant,nom) VALUES (09,'SANEFI PHARMA');
INSERT INTO fabricants (nrfabricant,nom) VALUES (10,'CHEFARO');
COMMIT;