INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
1, 'MEDICAMENTS DU SYSTEME CARDIO-VASCULAIRE'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
2, 'MEDICAMENTS DU SYSTEME GASTRO-INTESTINAL'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
3, 'MEDICAMENTS DU SYSTEME ANALGESIQUE'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
4, 'MEDICAMENTS DU SYSTEME NERVEUX'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
5, 'MEDICAMENTS DU SYSTEME HORMONAL'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
6, 'MEDICAMENTS DU SYSTEME RESPIRATOIRE'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
7, 'MEDICAMENTS ANTI-INFECTIEUX'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
8, 'VACCINS-GAMMAGLOBULINES-SERUMS'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
9, 'MEDICAMENTS ANTITUMORAUX'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
10, 'MEDICAMENTS AGISSANT SUR L''IMMUNITE'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
11, 'MEDICAMENTS UTILISES EN ANESTHERIOLOGIE'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
12, 'MINERAUX-VITAMINES-TONIQUES'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
13, 'TRAITEMENT DES INTOXICATIONS'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
14, 'MEDICAMENTS A USAGE EXTERNE (DERMATOLOGIE)'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
15, 'MEDICAMENTS A USAGE EXTERNE (OPHTALMOLOGIE)'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
16, 'MEDICAMENTS A USAGE EXTERNE (OTOLOGIE)'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
17, 'MEDICAMENTS A USAGE EXTERNE (STOMATOLOGIE)'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
18, 'MEDICAMENTS A USAGE EXTERNE (GYNECOLOGIE LOCALE)'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
19, 'ANESTHESIQUES LOCAUX'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
20, 'AGENTS DE DIAGNOSTIC'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
21, 'PERFUSIONS'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
22, 'TISANES'); 
INSERT INTO GROUPES ( NRGROUPE, LIBELLE ) VALUES ( 
23, 'ALIMENTS SPECIAUX'); 
COMMIT;
 
