INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M001', 'DAFALGAN 500mg', 'COMPRIMES', 'BOITE DE 30', 'ANALSESIQUE/ANTIPYRETIQUE'
, 3, 1); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M002', 'DAFALGAN CODEINE', 'COMPRIMES EFFERVESCENTS', 'BOITE DE 32', 'ANALSESIQUE/ANTIPYRETIQUE'
, 3, 1); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M003', 'DAFALGAN 1g', 'COMPRIMES EFFERVESCENTS', 'BOITE DE 32', 'ANALSESIQUE/ANTIPYRETIQUE'
, 3, 1); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M004', 'CURPOL', 'SIROP', '180ML', 'ANALSESIQUE/ANTIPYRETIQUE', 3, 2); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M005', 'EFFERALGAN C', 'COMPRIMES EFFERVESCENTS', 'BOITE DE 20', 'ANALSESIQUE/ANTIPYRETIQUE'
, 3, 1); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M006', 'ASPRO 500', 'COMPRIMES', 'BOITE DE 20', 'ANALSESIQUE/ANTIPYRETIQUE', 3, 3); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M007', 'ASPRO C', 'SACHETS', 'BOITE DE 10', 'ANALSESIQUE/ANTIPYRETIQUE', 3, 3); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M008', 'EFFERBALGINE', 'COMPRIMES EFFERVESCENTS', 'BOITE DE 20', 'ANALSESIQUE/ANTIPYRETIQUE'
, 3, 4); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M009', 'SEDERGINE', 'COMPRIMES EFFERVESCENTS', 'BOITE DE 24', 'ANALSESIQUE/ANTIPYRETIQUE'
, 3, 1); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M010', 'ISOTEN', 'COMPRIMES ', 'BOITE DE 28', 'ANTI HYPERTENSEUR', 1, 5); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M011', 'EMCONCOR MITIS', 'COMPRIMES', 'BOITE DE 28', 'ANTI HYPERTENSEUR', 1, 6); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M012', 'EMCORETIC', 'COMPRIMES ', 'BOITE DE 56', 'ANTI HYPERTENSEUR', 1, 6); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M013', 'DICHLOTRIDE', 'COMPRIMES ', 'BOITE DE 25', 'ANTI HYPERTENSEUR', 1, 7); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M014', 'LIPITOR 10', 'COMPRIMES ', 'BOITE DE 84', 'HYPO LIP‚MIANT', 1, 8); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M015', 'LIPITOR 20', 'COMPRIMES ', 'BOITE DE 28', 'HYPO LIP‚MIANT', 1, 8); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M016', 'HYPERLIPEN', 'CAPSULES', 'BOITE DE 30', 'HYPO LIP‚MIANT', 1, 9); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M017', 'CREMICORT-H', 'CREME', 'TUBE 20G', 'DERMATOSE', 14, 10); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M018', 'TERRA-CORTRIL', 'ONGUANT', 'TUBE 15G', 'DERMATOSE', 14, 8); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M019', 'MINOCIN', 'CAPSULES', 'BOITE DE 20', 'ANTIBIOTIQUE', 7, 5); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M020', 'MINOTAB-100', 'COMPRIMES ', 'BOITE DE 20', 'ANTIBIOTIQUE', 7, 5); 
INSERT INTO MEDICAMENTS ( NRMEDICAMENT, DENOMINATION, TYPE, CONDITIONNEMENT, INDICATIONS, NRGROUPE,
NRFABRICANT ) VALUES ( 
'M021', 'PENI-ORAL', 'COMPRIMES ', 'BOITE DE 15', 'ANTIBIOTIQUE', 7, 5); 
COMMIT;
 
