INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AF', 'AFGHANISTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ZA', 'AFRIQUE DU SUD'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AL', 'ALBANIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'DZ', 'ALGERIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'DE', 'ALLEMAGNE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AD', 'ANDORRE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AO', 'ANGOLA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AI', 'ANGUILLA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AQ', 'ANTARCTIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AG', 'ANTIGUA-ET-BARBUDA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AN', 'ANTILLES NEERLANDAISES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SA', 'ARABIE SAOUDITE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AR', 'ARGENTINE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AM', 'ARMENIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AW', 'ARUBA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AU', 'AUSTRALIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AT', 'AUTRICHE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AZ', 'AZERBAIDJAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BS', 'BAHAMAS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BH', 'BAHREIN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BD', 'BANGLADESH'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BB', 'BARBADE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BY', 'BELARUS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BE', 'BELGIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BZ', 'BELIZE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BJ', 'BENIN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BM', 'BERMUDES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BT', 'BHOUTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BO', 'BOLIVIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BA', 'BOSNIE-HERZEGOVINE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BW', 'BOTSWANA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BV', 'BOUVET, ILE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BR', 'BRESIL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BN', 'BRUNEI DARUSSALAM'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BG', 'BULGARIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BF', 'BURKINA FASO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'BI', 'BURUNDI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KY', 'CAIMANES, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KH', 'CAMBODGE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CM', 'CAMEROUN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CA', 'CANADA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CV', 'CAP-VERT'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CF', 'CENTRAFRICAINE, REPUBLIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CL', 'CHILI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CN', 'CHINE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CX', 'CHRISTMAS, ILE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CY', 'CHYPRE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CC', 'COCOS (KEELING), ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CO', 'COLOMBIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KM', 'COMORES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CG', 'CONGO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CD', 'CONGO, LA REPUBLIQUE DEMOCRATIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CK', 'COOK, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KR', 'COREE, REPUBLIQUE DE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KP', 'COREE, REPUBLIQUE POPULAIRE DEMOCR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CR', 'COSTA RICA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CI', 'COTE D''IVOIRE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'HR', 'CROATIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CU', 'CUBA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'DK', 'DANEMARK'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'DJ', 'DJIBOUTI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'DO', 'DOMINICAINE, REPUBLIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'DM', 'DOMINIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'EG', 'EGYPTE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SV', 'EL SALVADOR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AE', 'EMIRATS ARABES UNIS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'EC', 'EQUATEUR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ER', 'ERYTHREE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ES', 'ESPAGNE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'EE', 'ESTONIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'US', 'ETATS-UNIS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ET', 'ETHIOPIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'FK', 'FALKLAND, ILES (MALVINAS)'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'FO', 'FEROE, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'FJ', 'FIDJI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'FI', 'FINLANDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'FR', 'FRANCE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GA', 'GABON'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GM', 'GAMBIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GE', 'GEORGIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GS', 'GEORGIE DU SUD ET LES ILES SANDWIC'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GH', 'GHANA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GI', 'GIBRALTAR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GR', 'GRECE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GD', 'GRENADE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GL', 'GROENLAND'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GP', 'GUADELOUPE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GU', 'GUAM'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GT', 'GUATEMALA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GN', 'GUINEE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GW', 'GUINEE-BISSAU'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GQ', 'GUINEE EQUATORIALE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GY', 'GUYANA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GF', 'GUYANE FRANCAISE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'HT', 'HAITI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'HM', 'HEARD, ILE ET MCDONALD, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'HN', 'HONDURAS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'HK', 'HONG-KONG'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'HU', 'HONGRIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'UM', 'ILES MINEURES ELOIGNEES DES ETATS-UNIS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VG', 'ILES VIERGES BRITANNIQUES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VI', 'ILES VIERGES DES ETATS-UNIS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IN', 'INDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ID', 'INDONESIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IR', 'IRAN, REPUBLIQUE ISLAMIQUE D''IRAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IQ', 'IRAQ'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IE', 'IRLANDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IS', 'ISLANDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IL', 'ISRAEL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IT', 'ITALIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'JM', 'JAMAIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'JP', 'JAPON'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'JO', 'JORDANIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KZ', 'KAZAKHSTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KE', 'KENYA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KG', 'KIRGHIZISTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KI', 'KIRIBATI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KW', 'KOWEIT'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LA', 'LAO, REPUBLIQUE DEMOCRATIQUE POPUL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LS', 'LESOTHO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LV', 'LETTONIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LB', 'LIBAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LR', 'LIBERIA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LY', 'LIBYENNE, JAMAHIRIYA ARABE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LI', 'LIECHTENSTEIN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LT', 'LITUANIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LU', 'LUXEMBOURG'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MO', 'MACAO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MK', 'MACEDOINE, L''EX-REPUBLIQUE YOUGOSL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MG', 'MADAGASCAR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MY', 'MALAISIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MW', 'MALAWI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MV', 'MALDIVES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ML', 'MALI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MT', 'MALTE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MP', 'MARIANNES DU NORD, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MA', 'MAROC'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MH', 'MARSHALL, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MQ', 'MARTINIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MU', 'MAURICE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MR', 'MAURITANIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'YT', 'MAYOTTE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MX', 'MEXIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'FM', 'MICRONESIE, ETATS FEDERES DE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MD', 'MOLDOVA, REPUBLIQUE DE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MC', 'MONACO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MN', 'MONGOLIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MS', 'MONTSERRAT'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MZ', 'MOZAMBIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'MM', 'MYANMAR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NA', 'NAMIBIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NR', 'NAURU'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NP', 'NEPAL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NI', 'NICARAGUA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NE', 'NIGER'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NG', 'NIGERIA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NU', 'NIUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NF', 'NORFOLK, ILE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NO', 'NORVEGE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NC', 'NOUVELLE-CALEDONIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NZ', 'NOUVELLE-ZELANDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'IO', 'OCEAN INDIEN, TERRITOIRE BRITANNIQ'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'OM', 'OMAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'UG', 'OUGANDA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'UZ', 'OUZBEKISTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PK', 'PAKISTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PW', 'PALAOS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PS', 'PALESTINIEN OCCUPE, TERRITOIRE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PA', 'PANAMA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PG', 'PAPOUASIE-NOUVELLE-GUINEE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PY', 'PARAGUAY'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'NL', 'PAYS-BAS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PE', 'PEROU'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PH', 'PHILIPPINES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PN', 'PITCAIRN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PL', 'POLOGNE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PF', 'POLYNESIE FRANCAISE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PR', 'PORTO RICO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PT', 'PORTUGAL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'QA', 'QATAR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'RE', 'REUNION'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'RO', 'ROUMANIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'GB', 'ROYAUME-UNI'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'RU', 'RUSSIE, FEDERATION DE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'RW', 'RWANDA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'EH', 'SAHARA OCCIDENTAL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SH', 'SAINTE-HELENE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LC', 'SAINTE-LUCIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'KN', 'SAINT-KITTS-ET-NEVIS'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SM', 'SAINT-MARIN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'PM', 'SAINT-PIERRE-ET-MIQUELON'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VA', 'SAINT-SIEGE (ETAT DE LA CITE DU VA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VC', 'SAINT-VINCENT-ET-LES GRENADINES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SB', 'SALOMON, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'WS', 'SAMOA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'AS', 'SAMOA AMERICAINES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ST', 'SAO TOME-ET-PRINCIPE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SN', 'SENEGAL'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CS', 'SERBIE-ET-MONTENEGRO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SC', 'SEYCHELLES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SL', 'SIERRA LEONE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SG', 'SINGAPOUR'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SK', 'SLOVAQUIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SI', 'SLOVENIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SO', 'SOMALIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SD', 'SOUDAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'LK', 'SRI LANKA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SE', 'SUEDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CH', 'SUISSE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SR', 'SURINAME'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SJ', 'SVALBARD ET ILE JAN MAYEN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SZ', 'SWAZILAND'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'SY', 'SYRIENNE, REPUBLIQUE ARABE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TJ', 'TADJIKISTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TW', 'TAIWAN, PROVINCE DE CHINE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TZ', 'TANZANIE, REPUBLIQUE-UNIE DE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TD', 'TCHAD'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'CZ', 'TCHEQUE, REPUBLIQUE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TF', 'TERRES AUSTRALES FRANCAISES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TH', 'THAILANDE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TL', 'TIMOR-LESTE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TG', 'TOGO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TK', 'TOKELAU'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TO', 'TONGA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TT', 'TRINITE-ET-TOBAGO'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TN', 'TUNISIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TM', 'TURKMENISTAN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TC', 'TURKS ET CAIQUES, ILES'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TR', 'TURQUIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'TV', 'TUVALU'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'UA', 'UKRAINE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'UY', 'URUGUAY'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VU', 'VANUATU'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VE', 'VENEZUELA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'VN', 'VIET NAM'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'WF', 'WALLIS ET FUTUNA'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'YE', 'YEMEN'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ZM', 'ZAMBIE'); 
INSERT INTO PAYS ( CODEPAYS, LIBELLE ) VALUES ( 
'ZW', 'ZIMBABWE'); 
COMMIT;
 
