INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S001', 'ANESTHESIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S002', 'CARDIOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S003', 'CHIRURGIE ABDOMINALE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S004', 'CHIRURGIE CARDIO-VASCULAIRE ET THORACIQUE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S005', 'CHIRURGIE DE LA MAIN - MICROCHIRURGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S006', 'CHIRURGIE MAXILLO-FACIALE ET PLASTIQUE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S007', 'CHIRURGIE ORO-FACIALE ET ESTHETIQUE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S008', 'CHIRURGIE ORTHOPEDIQUE - TRAUMATOLOGIE '); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S009', 'DERMATOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S010', 'ENDOCRINOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S011', 'GASTRO-ENTEROLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S013', 'HEMATOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S014', 'NEPHROLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S015', 'NEUROCHIRURGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S016', 'NEUROLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S017', 'NEUROPSYCHIATRIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S018', 'ONCOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S019', 'OPHTALMOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S020', 'PNEUMOLOGIE ET ALLERGOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S021', 'RADIOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S022', 'RHUMATOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S023', 'SENOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S024', 'UROLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S025', 'OTO-RHINO-LARYNGOLOGIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S026', 'GENETIQUE HUMAINE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S027', 'RESONANCE MAGNETIQUE NUCLEAIRE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S028', 'GERIATRIE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S029', 'GYNECOLOGIE OBSTETRIQUE'); 
INSERT INTO SERVICES ( NRSERVICE, LIBELLE ) VALUES ( 
'S030', 'PEDIATRIE'); 
COMMIT;
 
