INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'151', 'CHIRURGIE ORTHOPEDIQUE - TRAUMATOLOGIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'170', 'NEUROCHIRURGIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'370', 'OPHTALMOLOGIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'410', 'ORL'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'340', 'GYNECOLOGIE OBSTETRIQUE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'760', 'NEUROPSYCHIATRIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'591', 'CARDIOLOGIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'650', 'GASTRO-ENTEROLOGIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'690', 'PEDIATRIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'567', 'DERMATOLOGIE'); 
INSERT INTO SPECIALITES ( SPECIALITE, LIBELLE ) VALUES ( 
'001', 'MEDECINE GENERALE'); 
commit;
 
