INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S001', 'TETRACYCLINE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S002', 'PENICILLINE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S003', 'ACIDE ACETYLSALICYLIQUE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S004', 'PARACETAMOL'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S005', 'CODEINE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S006', 'ACIDE ASCORBIQUE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S007', 'BISOPROLOL'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S008', 'HYDROCHLOROTHIAZIDE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S009', 'ATORVASTATINE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S010', 'CIPROFIBRATE'); 
INSERT INTO SUBSTANCES ( NRSUBSTANCE, NOM ) VALUES ( 
'S011', 'HYDROCORTISONE'); 
commit;
 
