/*
drop table CS_FILMS cascade constraints;
drop table CS_PAYS cascade constraints;
drop table CS_INTERVENANTS cascade constraints;
drop table CS_FONCTIONS cascade constraints;
drop table CS_TRAVAILLER cascade constraints;
drop table CS_PRODUIRE cascade constraints;
drop table CS_CATEGORIES cascade constraints;
drop table CS_FC cascade constraints;
drop table CS_SEANCES cascade constraints;
drop table CS_SALLES cascade constraints;
drop table CS_ADHERENTS cascade constraints;
drop table CS_RESERVATIONS cascade constraints;
*/

CREATE TABLE CS_FILMS (
	NUMFILM NUMBER(4),
	TITRE VARCHAR2(40) CONSTRAINT FILMS_TITRE NOT NULL ENABLE,
	ANNEE NUMBER(4) CONSTRAINT FILMS_ANNEE NOT NULL ENABLE,
	DUREE NUMBER(3) CONSTRAINT FILMS_DUREE NOT NULL ENABLE,
	CONSTRAINT PK_FILMS PRIMARY KEY(NUMFILM)
);

CREATE TABLE CS_PAYS (
	CODEPAYS CHAR(2),
	DESIGNATION VARCHAR2(20) CONSTRAINT PAYS_DESIGNATION NOT NULL ENABLE,
	CONSTRAINT PK_PAYS PRIMARY KEY(CODEPAYS)
);

CREATE TABLE CS_INTERVENANTS (
	NUMINTERVENANT NUMBER(4),
	NOM VARCHAR2(30) CONSTRAINT INTERVENANTS_NOM NOT NULL ENABLE,
	PRENOM VARCHAR2(30),
	NATIONALITE CHAR(2),
	SEXE CHAR(1),
	CONSTRAINT INTERVENANTS_SEXE CHECK (UPPER(SEXE) IN ('F', 'M')) ENABLE,
	CONSTRAINT PK_INTERVENANTS PRIMARY KEY (NUMINTERVENANT),
	CONSTRAINT FK_INTERVENANTSPAYS FOREIGN KEY (NATIONALITE) REFERENCES CS_PAYS (CODEPAYS) ENABLE
);

CREATE TABLE CS_FONCTIONS (
	NUMFONCTION NUMBER(4),
	FONCTION VARCHAR2(30) CONSTRAINT FONCTIONS_NOM NOT NULL ENABLE,
	CONSTRAINT PK_FONCTIONS PRIMARY KEY(NUMFONCTION)
);

CREATE TABLE CS_TRAVAILLER (
	NUMFILM NUMBER(4),
	NUMFONCTION NUMBER(4),
	NUMINTERVENANT NUMBER(4),
	CONSTRAINT PK_TRAVAILLER PRIMARY KEY(NUMFILM, NUMFONCTION, NUMINTERVENANT),
	CONSTRAINT FK_TRAVAILLERFILMS FOREIGN KEY(NUMFILM) REFERENCES CS_FILMS (NUMFILM) ENABLE,
	CONSTRAINT FK_TRAVAILLERFONCTIONS FOREIGN KEY(NUMFONCTION) REFERENCES CS_FONCTIONS (NUMFONCTION) ENABLE,
	CONSTRAINT FK_TRAVAILLERINTERVENANTS FOREIGN KEY(NUMINTERVENANT) REFERENCES CS_INTERVENANTS (NUMINTERVENANT) ENABLE
);

CREATE TABLE CS_PRODUIRE (
	NUMFILM NUMBER(4),
	CODEPAYS CHAR(2),
	CONSTRAINT PK_PRODUIRE PRIMARY KEY(NUMFILM, CODEPAYS),
	CONSTRAINT FK_PRODUIREFILMS FOREIGN KEY(NUMFILM) REFERENCES CS_FILMS (NUMFILM) ENABLE,
	CONSTRAINT FK_PRODUIREPAYS FOREIGN KEY(CODEPAYS) REFERENCES CS_PAYS (CODEPAYS) ENABLE
);

CREATE TABLE CS_CATEGORIES (
	NUMCAT NUMBER(2),
	LIBELLE VARCHAR2(20) CONSTRAINT CATEGORIES_LIBELLE NOT NULL ENABLE,
	CONSTRAINT PK_CAT PRIMARY KEY(NUMCAT)
);

CREATE TABLE CS_FC (
	NUMFILM NUMBER(4),
	NUMCAT NUMBER(2),
	CONSTRAINT PK_FC PRIMARY KEY(NUMFILM, NUMCAT),
	CONSTRAINT FK_FCFILMS FOREIGN KEY(NUMFILM) REFERENCES CS_FILMS (NUMFILM) ENABLE,
	CONSTRAINT FK_FCCATEGORIES FOREIGN KEY(NUMCAT) REFERENCES CS_CATEGORIES (NUMCAT) ENABLE
);

CREATE TABLE CS_SALLES (
	NUMSALLE NUMBER(3),
	NOMSALLE VARCHAR2(30) CONSTRAINT SALLES_NOMSALLE NOT NULL ENABLE,
	ADRESSESALLE VARCHAR2(50),
	VILLESALLE VARCHAR2(30) CONSTRAINT SALLES_VILLESALLE NOT NULL ENABLE,
	TELEPHONE CHAR(14),
	CONSTRAINT SALLES_TELEPHONE CHECK (TELEPHONE LIKE ('__ __ __ __ __')) ENABLE,
	CONSTRAINT PK_SALLES PRIMARY KEY(NUMSALLE)
);

CREATE TABLE CS_SEANCES (
	NUMFILM NUMBER(4),
	NUMSALLE NUMBER(3),
	JOUR CHAR(8),
	HEUREDEB CHAR(5),
	CONSTRAINT SEANCES_HEUREDEB CHECK (HEUREDEB LIKE ('__h__')) ENABLE,
	CONSTRAINT PK_SEANCES PRIMARY KEY(NUMFILM, NUMSALLE, JOUR, HEUREDEB),
	CONSTRAINT FK_SEANCESFILMS FOREIGN KEY(NUMFILM) REFERENCES CS_FILMS (NUMFILM) ENABLE,
	CONSTRAINT FK_SEANCESSALLES FOREIGN KEY(NUMSALLE) REFERENCES CS_SALLES (NUMSALLE) ENABLE
);

CREATE TABLE CS_ADHERENTS (
	NUMADHE NUMBER(5),
	NOMADHE VARCHAR2(30) CONSTRAINT ADHERENTS_NOMADHE NOT NULL ENABLE,
	PRENOMADHE VARCHAR2(30),
	ADRESSE VARCHAR2(50),
	CODE_POSTAL CHAR(5),
	VILLE VARCHAR2(30) CONSTRAINT ADHERENTS_VILLE NOT NULL ENABLE,
	ORDRECOTISATION CHAR(1),
	CONSTRAINT ADHERENTS_CODEPOSTAL CHECK (CODE_POSTAL LIKE ('_____')) ENABLE,
	CONSTRAINT PK_ADHE PRIMARY KEY(NUMADHE)
);

CREATE TABLE CS_RESERVATIONS (
	NUMFILM NUMBER(4),
	NUMSALLE NUMBER(3),
	JOUR CHAR(8),
	HEUREDEB CHAR(5),
	NUMADHE NUMBER(5),
	NBPLACES NUMBER(3) CONSTRAINT RESERVATIONS_NBPLACES NOT NULL ENABLE,
	PAYE CHAR(1),
	MODEPAIEMENT CHAR(2),
	CONSTRAINT RESERVATIONS_PAYE CHECK (UPPER(PAYE) IN ('O', 'N')) ENABLE,
	CONSTRAINT RESERVATIONS_MODEPAIEMENT CHECK (UPPER(MODEPAIEMENT) IN ('ES', 'CH', 'CB')) ENABLE,
	CONSTRAINT RESERVATIONS_HEUREDEB CHECK (HEUREDEB LIKE ('__h__')) ENABLE,
	CONSTRAINT PK_RESERV PRIMARY KEY(NUMFILM, NUMSALLE, JOUR, HEUREDEB, NUMADHE),
	CONSTRAINT FK_RESERVATIONSSEANCES FOREIGN KEY(NUMFILM, NUMSALLE, JOUR, HEUREDEB) REFERENCES CS_SEANCES (NUMFILM, NUMSALLE, JOUR, HEUREDEB) ENABLE,
	CONSTRAINT FK_RESERVATIONSADHERENTS FOREIGN KEY(NUMADHE) REFERENCES CS_ADHERENTS (NUMADHE) ENABLE
);